#SPDX-License-Identifier: MIT-0
---
# Shared variables:
docker_repo_url: https://download.docker.com/linux
docker_yum_gpg_key: "{{ docker_repo_url }}/centos/gpg"
docker_packages_to_install:
  - docker-ce 
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

# RedHat specific variables:
docker_repo_rhel: "{{ docker_repo_url }}/rhel/docker-ce.repo"

# Debian specific variables:
docker_repo_debian: "{{ docker_repo_url }}/debian"

debian_prerequisites:
  - ca-certificates
  - curl
  - apt-transport-https

docker_apt_ansible_distribution: "{{ ansible_distribution if ansible_distribution_release != 'trixie' else 'debian' }}"
docker_distribution_release: "{{ ansible_distribution_release if ansible_distribution_release != 'trixie' else 'bookworm' }}"
docker_apt_release_channel: stable

docker_apt_gpg_key: "{{ docker_repo_url }}/{{ docker_apt_ansible_distribution | lower }}/gpg"
docker_gpg_key_file_path: "/etc/apt/keyrings/docker.gpg"
docker_apt_filename: "docker"

docker_apt_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'armhf' if ansible_architecture == 'armv7l' else 'amd64' }}"
docker_apt_repository: "deb [arch={{ docker_apt_arch }} signed-by=/etc/apt/keyrings/docker.asc] {{ docker_repo_url }}/{{ docker_apt_ansible_distribution | lower }} {{ docker_distribution_release }} {{ docker_apt_release_channel }}"
