---
driver:
  name: docker
platforms:
  - name: instance-rockylinux
    image: rockylinux:9.3
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_user: root
      verbosity: 2