---
- include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Install requirements
  ansible.builtin.package:
    name: "{{ virtualbox_requirements }}"
    state: present

- name: Install virtualbox
  ansible.builtin.package:
    name: "{{ virtualbox_package }}"
    state: present
  notify:
    - Run vboxconfig