- name: Import rpm key
  ansible.builtin.rpm_key:
    state: present
    key: "{{ item }}"
  loop: "{{ virtualbox_keys }}"
  loop_control:
    label: "{{ item | basename }}"

- name: Place yum repository
  ansible.builtin.yum_repository:
    name: virtualbox
    description: Fedora $releasever - $basearch - VirtualBox
    baseurl: "{{ virtualbox_yum_baseurl }}"
    gpgcheck: true

