#SPDX-License-Identifier: MIT-0
---
- include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Docker packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ docker_packages_to_install }}"

- name: Ensure Docker group exists
  group:
    name: docker
    state: present

- name: Add user to Docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: yes