---
- name: Ensure old versions of Docker are not installed.
  package:
    name:
      - docker
      - docker-common
      - docker-engine
    state: absent

- name: Install DNF plugins
  package:
    name:
      - dnf-plugins-core
    state: present

- name: Add Docker repository
  get_url:
    url: "{{ docker_repo_rhel }}"
    dest: /etc/yum.repos.d/docker-ce.repo
  register: add_repository