version: '3.8'
 
services:
  bind9:
    image: ubuntu/bind9
    container_name: bind9
    environment:
      - BIND9_USER=root
      - TZ=Asia/Almaty
    ports:
      - "53:53"
      - "53:53/udp"
    volumes:
      - /etc/bind:/etc/bind
    restart: unless-stopped